// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnTsEX24acNxdmQIIzBYDs8f5GBJlide0',
    appId: '1:675811772534:web:c714696e25d24a85def757',
    messagingSenderId: '675811772534',
    projectId: 'dishgenie-8d35f',
    authDomain: 'dishgenie-8d35f.firebaseapp.com',
    storageBucket: 'dishgenie-8d35f.firebasestorage.app',
    measurementId: 'G-X811YWF3QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAODRkxr4wML3oB6qU0oFNHNPdCS7jlQ58',
    appId: '1:675811772534:android:7fcecdd128e15440def757',
    messagingSenderId: '675811772534',
    projectId: 'dishgenie-8d35f',
    storageBucket: 'dishgenie-8d35f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRh12xF51HSG231J8O9Z2aDJrxUIaiEYc',
    appId: '1:675811772534:ios:ce06abdb7901278bdef757',
    messagingSenderId: '675811772534',
    projectId: 'dishgenie-8d35f',
    storageBucket: 'dishgenie-8d35f.firebasestorage.app',
    iosBundleId: 'com.dishgenie.recipeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRh12xF51HSG231J8O9Z2aDJrxUIaiEYc',
    appId: '1:675811772534:ios:ce06abdb7901278bdef757',
    messagingSenderId: '675811772534',
    projectId: 'dishgenie-8d35f',
    storageBucket: 'dishgenie-8d35f.firebasestorage.app',
    iosBundleId: 'com.dishgenie.recipeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnTsEX24acNxdmQIIzBYDs8f5GBJlide0',
    appId: '1:675811772534:web:616468df47dd83fbdef757',
    messagingSenderId: '675811772534',
    projectId: 'dishgenie-8d35f',
    authDomain: 'dishgenie-8d35f.firebaseapp.com',
    storageBucket: 'dishgenie-8d35f.firebasestorage.app',
    measurementId: 'G-KS8JCTPFVS',
  );
}
